name = "Hugo Theme TechDoc"
license = "MIT"
licenselink = "https://github.com/thingsym/hugo-theme-techdoc/blob/master/LICENSE"
description = "A lightweight, simple documentation theme for Hugo"
homepage = "https://github.com/thingsym/hugo-theme-techdoc"
tags = ["documentation", "technical", "simple"]
features = ["search", "shortcodes"]
min_version = "0.62.0"

[author]
  name = "Thingsym"
  homepage = "https://thingsym.com/"